export const LOADING='LOADING'

export const GET_WEATHER_SUCCESS='GET_WEATHER_SUCCESS'

export const GET_WEATHER_FAILED='GET_WEATHER_FAILED'

export const GETFORECAST_SUCCESS='GETFORECAST_SUCCESS'
export const GETFORECAST_FAILED ='GETFORECAST_FAILED'

//search
export const SEARCHWEATHER='SEARCHWEATHER'